#!/bin/bash
# gen-stubs.sh OBJDIR - regenerate shim/kshim_stubs.c: one stopping stub per Linux symbol the
# vendored fs/ntfs references but neither the shim nor the core defines (objects built by cc1.sh).
set -euo pipefail
export LC_ALL=C
NM=/root/ros/RosBE-CI/i386/bin/i686-w64-mingw32-nm
cd "$1"
$NM -u *.o | awk 'NF>=1{print $NF}' | grep -v ':$' | sort -u > /tmp/ngs-undef.txt
$NM --defined-only *.o | awk 'NF==3{print $3}' | sort -u > /tmp/ngs-def.txt
echo '// SPDX-License-Identifier: GPL-2.0-or-later'
echo '/* Generated by gen-stubs.sh: Linux APIs referenced by fs/ntfs that the read-only NT port never calls. */'
echo 'void kshim_unimpl(const char *name) __attribute__((noreturn));'
comm -23 /tmp/ngs-undef.txt /tmp/ngs-def.txt | sed 's/^_//' | \
  grep -vE '^(ngos_.*|mem(cmp|cpy|move|set)|str(cmp|len|ncmp|chr|rchr|str|cpy|ncpy|nlen)|__(u?div|u?mod)di3)$' | \
  while read -r s; do echo "void $s(void) { kshim_unimpl(\"$s\"); }"; done
