/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Linux errno values (include/uapi/asm-generic/errno-base.h and errno.h). */
#ifndef KSHIM_ERRNO_H
#define KSHIM_ERRNO_H
#undef EPERM
#define EPERM 1
#define ENOENT 2
#define ESRCH 3
#define EINTR 4
#define EIO 5
#define ENXIO 6
#define E2BIG 7
#define ENOEXEC 8
#define EBADF 9
#define ECHILD 10
#define EAGAIN 11
#define ENOMEM 12
#define EACCES 13
#define EFAULT 14
#define ENOTBLK 15
#define EBUSY 16
#define EEXIST 17
#define EXDEV 18
#define ENODEV 19
#define ENOTDIR 20
#define EISDIR 21
#define EINVAL 22
#define ENFILE 23
#define EMFILE 24
#define ENOTTY 25
#define ETXTBSY 26
#define EFBIG 27
#define ENOSPC 28
#define ESPIPE 29
#define EROFS 30
#define EMLINK 31
#define EPIPE 32
#define EDOM 33
#define ERANGE 34
#define EDEADLK 35
#define ENAMETOOLONG 36
#define ENOLCK 37
#define ENOSYS 38
#define ENOTEMPTY 39
#define ELOOP 40
#define EWOULDBLOCK EAGAIN
#define ENOMSG 42
#define ENODATA 61
#define ETIME 62
#define ENOLINK 67
#define EPROTO 71
#define EBADMSG 74
#define EOVERFLOW 75
#define EILSEQ 84
#define EUSERS 87
#define ENOTSOCK 88
#define EMSGSIZE 90
#define EOPNOTSUPP 95
#define ENOTSUP EOPNOTSUPP
#define ENOBUFS 105
#define ETIMEDOUT 110
#define EALREADY 114
#define EINPROGRESS 115
#define ESTALE 116
#define EUCLEAN 117
#define EREMOTEIO 121
#define EDQUOT 122
#define ECANCELED 125
#endif
