#!/usr/bin/env python3
# Generate the syscall table for the kvfuzz tool from ReactOS's own tables:
#   ntoskrnl/sysfuncs.lst   -> NT syscalls (name + 32-bit arg count)
#   win32ss/w32ksvc32.h     -> win32k syscalls (SVC_(name, argc), index|0x1000)
# Usage: gen_syscalls.py <sysfuncs.lst> <w32ksvc32.h> <out.h>
import sys, re

def main():
    nt_lst, w32_h, out = sys.argv[1], sys.argv[2], sys.argv[3]
    rows = []

    for line in open(nt_lst):
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        parts = line.split()
        if len(parts) >= 2 and parts[0].startswith("Nt"):
            rows.append((parts[0], int(parts[1]), "KF_NT", 0))

    idx = 0
    svc = re.compile(r"SVC_\(\s*([A-Za-z0-9_]+)\s*,\s*(\d+)\s*\)")
    for line in open(w32_h):
        m = svc.search(line)
        if not m:
            continue
        name, argc = m.group(1), int(m.group(2))
        rows.append(("Nt" + name, argc, "KF_W32", idx))
        idx += 1

    with open(out, "w") as f:
        f.write("/* Generated by gen_syscalls.py from ReactOS syscall tables. */\n")
        f.write("#define KF_NT  0\n#define KF_W32 1\n")
        f.write("typedef struct _KF_SYSCALL {\n")
        f.write("    const char *Name; unsigned char Args; unsigned char Target; unsigned short W32Index;\n")
        f.write("} KF_SYSCALL;\n")
        f.write("static const KF_SYSCALL KfSyscalls[] = {\n")
        for name, argc, tgt, w in rows:
            f.write('    {"%s", %d, %s, %d},\n' % (name, argc, tgt, w))
        f.write("};\n")
        f.write("static const unsigned KfSyscallCount = %d;\n" % len(rows))
    sys.stderr.write("gen_syscalls: %d entries (%d NT, %d win32k)\n" %
                     (len(rows), sum(1 for r in rows if r[2]=="KF_NT"), idx))

if __name__ == "__main__":
    main()
